modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
displayURL="https://github.com/Fayberr/Infinite-Trading-Minecraft-Mod"
issueTrackerURL="https://github.com/Fayberr/Infinite-Trading-Minecraft-Mod/issues"
sourceURL="https://github.com/Fayberr/Infinite-Trading-Minecraft-Mod"
authors="Fayber"
description="Allows OPs and singleplayer users to enable infinite trading for specific players. Works on Dedicated Servers and in Singleplayer worlds."
displayTest="IGNORE_ALL_VERSION"

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version_range},)"
ordering="NONE"
side="BOTH"
